### PR TITLE
add retry dependency to pip install

### PR DESCRIPTION
**Pull request by TomRyan-321**
missing dependency from upstream project

### CODE REVIEW

**Comment by henriquevcosta** [comment]
@redhatrises we're seeing builds fail in my org which look like they'd be fix by this, would you be able to share the timeline for a new release of the action including this change?

**Comment by redhatrises** [comment]
Shouldn't have to wait for releases. Should be able to use `@main`

**Comment by henriquevcosta** [comment]
Thanks for the quick reply. Do you mean to say that main will always be stable and can reliably be pointed to, or that it's still best to point to released versions but as a workaround I can use main for now?

**Comment by bodgit** [comment]
> Shouldn't have to wait for releases. Should be able to use `@main`

Am I the only one finding that advice slightly ironic from a company such as CrowdStrike?

**Pull request merged**
